CREATE DATABASE COVID ;
USE COVID;
CREATE TABLE COVID_CASES_COUNTRIES(
COUNTRY_ID INT,
COUNTRY_NAME varchar(35),
COUNTRY_TOTAL_CASES bigint,
COUNTRY_TOTAL_DEATHS bigint,
COUNTRY_REGION varchar(50),
primary key (COUNTRY_ID , COUNTRY_NAME) 
);

CREATE TABLE VACCINATION_DETAILS(
VACCINATION_COUNTRY_NAME varchar(50),
VACCINATION_TOTAL_DOSES bigint,
VACCINATION_PEOPLE_VACCINATED BIGINT,
VACCINATION_PERCENTAGE_VACCINATED FLOAT,
PRIMARY KEY (VACCINATION_COUNTRY_NAME)
);
SELECT *FROM COVID_CASES_COUNTRIES;
SELECT * FROM VACCINATION_DETAILS;
desc COVID_CASES_COUNTRIES;
desc VACCINATION_DETAILS;

ALTER TABLE COVID_CASES_COUNTRIES modify COUNTRY_TOTAL_CASES bigint DEFAULT FALSE;
ALTER TABLE VACCINATION_DETAILS modify VACCINATION_PERCENTAGE_VACCINATED DOUBLE ;
ALTER TABLE VACCINATION_DETAILS ADD  VACCINATION_COUNTRY_ID INT ;
 

desc COVID_CASES_COUNTRIES;
desc VACCINATION_DETAILS;

INSERT INTO COVID_CASES_COUNTRIES VALUES(1,'UNITED STATES' , 32361280 , 580756, 'North America');
INSERT INTO COVID_CASES_COUNTRIES VALUES(2,'INDIA' , 14788109 , 177168, 'Asia');
INSERT INTO COVID_CASES_COUNTRIES VALUES(3,'BRAZIL' , 13900134 , 371889, 'South America');
INSERT INTO COVID_CASES_COUNTRIES VALUES(4,'FRANCE' , 5260182 , 100593, 'Europe');
INSERT INTO COVID_CASES_COUNTRIES VALUES(5,'RUSSIA' , 4702101 , 105582, 'Europe');
INSERT INTO COVID_CASES_COUNTRIES VALUES(6,'UNITED KINGDOM' , 4385938 , 127260, 'Europe');

UPDATE  COVID_CASES_COUNTRIES SET COUNTRY_TOTAL_CASES=4702102  WHERE COUNTRY_NAME = 'RUSSIA' ;
SELECT *FROM COVID_CASES_COUNTRIES;


INSERT INTO VACCINATION_DETAILS VALUES('UNITED STATES' , 202282923 , 80609818, 2.5, 1);
INSERT INTO VACCINATION_DETAILS VALUES('INDIA' , 119937541 , 15529157, 1.1,2);
INSERT INTO  VACCINATION_DETAILS VALUES('BRAZIL' , 32810523 , 8000733, 3.8,3);
INSERT INTO VACCINATION_DETAILS VALUES('FRANCE' , 16252560 , 4269590,6.4, 4);
INSERT INTO VACCINATION_DETAILS VALUES('RUSSIA' , 15469617 , 5738147,3.9, 5);
INSERT INTO VACCINATION_DETAILS VALUES('UNITED KINGDOM' , 41505768 ,8931547, 13.4, 6);

UPDATE  VACCINATION_DETAILS SET VACCINATION_TOTAL_DOSES=15469618 WHERE VACCINATION_COUNTRY_NAME = 'RUSSIA' ;
SELECT * FROM VACCINATION_DETAILS;

SELECT MIN(VACCINATION_PEOPLE_VACCINATED) FROM VACCINATION_DETAILS;
SELECT MAX(COUNTRY_TOTAL_DEATHS) FROM COVID_CASES_COUNTRIES;
SELECT SUM(COV.VACCINATION_TOTAL_DOSES) FROM VACCINATION_DETAILS AS COV;
SELECT AVG(VACCINATION_PERCENTAGE_VACCINATED) FROM VACCINATION_DETAILS;
SELECT COUNT(COUNTRY_NAME) FROM COVID_CASES_COUNTRIES;

SELECT * FROM COVID_CASES_COUNTRIES WHERE COUNTRY_NAME IN('Russia','India','France');
SELECT * FROM VACCINATION_DETAILS WHERE VACCINATION_PERCENTAGE_VACCINATED BETWEEN 5 AND 15;

SELECT * FROM COVID_CASES_COUNTRIES WHERE COUNTRY_NAME LIKE 'R%%A';
SELECT * FROM COVID_CASES_COUNTRIES WHERE COUNTRY_NAME LIKE '____E%';
SELECT * FROM COVID_CASES_COUNTRIES WHERE COUNTRY_NAME LIKE '_R%___%E';

INSERT INTO VACCINATION_DETAILS VALUES ('BANGLADESH',1720039,56788,4.5,7);
SELECT * FROM VACCINATION_DETAILS;

DELETE  FROM VACCINATION_DETAILS WHERE VACCINATION_TOTAL_DOSES=1720039 ;
SELECT * FROM VACCINATION_DETAILS;

CREATE TABLE DELETE_DETAILS(
DELETE_COUNTRY_NAME varchar(50),
DELETE_TOTAL_DOSES bigint
);
INSERT INTO DELETE_DETAILS VALUES('UNKNOWN',50);

TRUNCATE TABLE DELETE_DETAILS;

DROP database covid;


